### ISSUE TITLE
OSX+Chromeにてindexページが全く表示されなくなるケースがある

### ISSUE THREAD

**Issue by attakei** [nijibox/nijibox.github.com#2]
## 事象

下記のエラーが発生して、ページが何も表示されずに真っ白になります。

Chrome の開発者コンソールでのエラー内容

```
Uncaught TypeError: Object.assign is not a function
 setState @ (index):190
 navigated @ (index):175
 (anonymous function) @ (index):200
```
## 発生環境
- OS X Yosemite (10.10.5)
- Google Chrome バージョン 42.0.2311.152 (64-bit)

現時点では上記環境のみで確認（同一端末のSafariやiPhoneのChromeでは発生せず）

**Comment by attakei** [comment]
(こちらにもメモ)

そもそも、Chromeのバージョンが古いのが原因の可能性が極めて大
（正確には、v8エンジンのバージョン？）

**Comment by remore** [comment]
うすうす気づいてたんですが、Object.assign()が最近ブラウザでサポートされた記法なので、Polyfill書かないといけないなーとは思ってたんですがサボってました。すみません。
https://developer.mozilla.org/ja/docs/Web/JavaScript/Reference/Global_Objects/Object/assign

どこかのタイミングでPolyfill書いて対応します。※そもそも今のままだとIE未サポートぽいし

**Comment by remore** [comment]
@attakei Polyfill追加して動作改善された気がするんですが、確認してみてもらえますか？できたら、フッタの方にあるブログ記事 アーカイブのリンクも踏んでみてほしいかも
https://developer.microsoft.com/en-us/microsoft-edge/tools/screenshots/#http://tech.nijibox.jp

**Comment by attakei** [comment]
@remore 手持ちのChrome 42.0.2311.152 (64-bit)で問題なく表示・遷移できることが確認できました。

**Comment by remore** [comment]
🙆
