### ISSUE TITLE
記事のルートパスに年月を入れたほうが良いのではないか

### ISSUE THREAD

**Issue by mk2** [nijibox/nijibox.github.com#5]
- 現状記事のルートパスは、記事markdownファイル名から先頭の`yyyyMMdd`と末尾の`.md`を覗いた文字列が使われている
- なのでそこが同じだと同じルートパスの記事が発生する
- 年月を入れればユニークになる場合が多いので、入れることで今後記事を追加する際にユニークかどうかチェックする手間が省ける

**Comment by remore** [comment]
あ、slugがユニークにならないケースの可能性ですね。当初ちゃんと考えてなかったんだけど（slugがかっこ良く見えることを優先して設計した）、たしかによちよち.nbみたいな定期開催系のイベント記事とかだと、ユニークネスを担保するのがちょっと手間になりそうか。

ちょっと考えますね。slugの可読性というか読みやすさ、エレガントさをできるだけ損なわないように工夫できるならしたいので

**Comment by remore** [comment]
@mk2 ちょっと考えてみてるんですが、もう少しヒアリングしてもいいですか？

今回書いてくれた記事のslugが `yochiyochi-nb-2` となってると思うんですが、titleは `よちよち.NB 2016/06/27 レポート` となってますよね。slugと記事titleを一致させていないのは、何か理由ってあるんでしょうか。

元々のslugの想定として、titleと一致するような英語で読めるslugを書くことを想定していたので、このslugの使われ方はちょっと想定できてなかったかも。で、titleと等価なslugが書かれることを前提とするならば、slugが重複することってないのかなーと元々は思ってたのでした。

**Comment by mk2** [comment]
いえ、一致させていない理由は特にないです。最初`yochiyochi-nb`で書いたら被ったので、`-2`を足した感じです。

slugが英語で読めるものにするという規約があるのであればそうします。（あまりslugの慣習を知らないので、すいません） @remore

**Comment by remore** [comment]
@mk2 あ、そうですね。英語で読めるような文字列をslugにした方がなんとなくSEO friendlyな（≒readableな）URIになってよいかなと思ってます。ユニークなslugを作りうるのは書き手にとっての不利益なんですけど、今の段階ではslugの見た目含めて仕組みをシンプルに保つ上での割り切りとしたい感じです🙏

**Comment by mk2** [comment]
@remore 了解です。今後はそうするようにします。
